name: abagon_dao_objectory
version: 0.1.0
author: www.eldardo.org
description: A library to implement DAOs based on abagon_dao's specification and using objectory/mongo_dart as DB driver.
homepage: https://github.com/el-dardo/abagon_dao_objectory
dependencies:
  objectory: 0.1.9
  mongo_dart: 0.1.14
  abagon_dao:
    git: https://github.com/el-dardo/abagon_dao.git
dev_dependencies:
  unittest: any

#dependencies:
#  unittest: any