name: abagon_dao_objectory
version: 0.1.0
author: eldardo.org
description: A library to implement DAOs based on abagon_dao's specification and using objectory/mongo_dart as DB driver.
dependencies:
  objectory: 0.1.9
  mongo_dart: 0.1.14
  abagon_dao:
    path: /Users/Ivan/Documents/Dart/eldardo.org/abagon_dao
dev_dependencies:
  unittest: any

#dependencies:
#  unittest: any